# Generated by Django 6.1 on 2026-08-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20, null=True),
        ),
    ]
