# Generated by Django 6.1 on 2026-09-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_timing',
            field=models.CharField(choices=[('BEFORE_PICKUP', 'Pay Before Pickup'), ('ON_DELIVERY', 'Pay on Delivery')], default='BEFORE_PICKUP', max_length=20),
        ),
    ]
