# Generated by Django 6.1 on 2026-08-29 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('declared_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_type', models.CharField(choices=[('NORMAL', 'Normal Delivery'), ('EXPRESS', 'Express Delivery')], default='NORMAL', max_length=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('AWAITING_PICKUP', 'Awaiting Pickup'), ('PICKED_UP', 'Picked Up'), ('AT_ORIGIN', 'At Origin'), ('IN_TRANSIT', 'In Transit'), ('AT_DESTINATION', 'At Destination'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=30)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_parcels', to='transport.location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_parcels', to='transport.location')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_parcels', to=settings.AUTH_USER_MODEL)),
                ('transport_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='transport.transportroute')),
            ],
        ),
    ]
