# Generated by Django 6.1 on 2026-08-29 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_trackingsequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='delivery_type',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='declared_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
