# Generated by Django 6.1 on 2026-08-29 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_remove_parcel_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='delivery_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Delivery'), ('EXPRESS', 'Express Delivery')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
