# Generated by Django 6.1 on 2026-08-31 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_parcel_delivery_type_alter_parcel_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
