# Generated by Django 6.1 on 2026-08-29 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Parcel Created'), ('PICKUP_ASSIGNED', 'Pickup Assigned'), ('PICKED_UP', 'Picked Up'), ('AT_ORIGIN', 'At Origin'), ('HANDED_TO_TRANSPORT', 'Handed to Transport'), ('IN_TRANSIT', 'In Transit'), ('AT_DESTINATION', 'At Destination'), ('DELIVERY_ASSIGNED', 'Delivery Assigned'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED_DELIVERY', 'Failed Delivery'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_events', to='transport.location')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='parcels.parcel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_time'],
            },
        ),
    ]
