# Generated by Django 6.1 on 2026-08-31 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_parcel_delivery_type_alter_parcel_delivery_fee'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AT_ORIGIN', 'At Origin'), ('IN_TRANSIT', 'In Transit'), ('AT_DESTINATION', 'At Destination')], default='AT_ORIGIN', max_length=30)),
                ('received_at_origin_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at_destination_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_handover', to='parcels.parcel')),
                ('transport_route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='transport.transportroute')),
            ],
        ),
    ]
